### ISSUE TITLE
some errors to migrate

### ISSUE THREAD

**Issue by lewandowskit** [rokorolov/parus-basic-app#3]
i tray tests on this cms end migrate some errors
```
Migrated up successfully.
Yii Migration Tool (based on Yii v2.0.10)

Total 3 new migrations to be applied:
        m160914_124800_init_module_gallery
        m161107_074410_add_image_column_to_album_table
        m161107_075508_rename_album_aliase_to_album_alias_album_table

Apply the above migrations? (yes|no) [no]:yes
*** applying m160914_124800_init_module_gallery
    > create table {{%album}} ... done (time: 0.174s)
    > create table {{%album_lang}} ... done (time: 0.182s)
    > add primary key  on {{%album_lang}} (album_id,language) ... done (time: 0.289s)
    > add foreign key fk__album_lang_album_id__album_id: {{%album_lang}} (album_id) references {{%album}} (id) ... done (time: 0.475s)
    > add foreign key fk__album_lang_language__language_lang_code: {{%album_lang}} (language) references {{%language}} (lang_code) ...Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table `blog`.`#sql-2734_6f` (errno: 150 "Foreign key constraint is incorrectly formed")
The SQL being executed was: ALTER TABLE `album_lang` ADD CONSTRAINT `fk__album_lang_language__language_lang_code` FOREIGN KEY (`language`) REFERENCES `language` (`lang_code`) ON DELETE CASCADE ON UPDATE CASCADE'

in C:\xampp\htdocs\blog\vendor\yiisoft\yii2\db\Schema.php:631

Error Info:
Array
(
    [0] => HY000
    [1] => 1005
    [2] => Can't create table `blog`.`#sql-2734_6f` (errno: 150 "Foreign key constraint is incorrectly formed")
)

Stack trace:
#0 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\db\Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `al...')
#1 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\db\Migration.php(415): yii\db\Command->execute()
#2 C:\xampp\htdocs\blog\vendor\rokorolov\parus\src\gallery\migrations\m160914_124800_init_module_gallery.php(29): yii\db\Migration->addForeignKey('fk__album_lang_...', '{{%album_lang}}', 'language', '{{%language}}', 'lang_code', 'CASCADE', 'CASCADE')
#3 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(651): m160914_124800_init_module_gallery->up()
#4 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(163): yii\console\controllers\BaseMigrateController->migrateUp('m160914_124800_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('up', Array)
#9 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#10 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#11 C:\xampp\htdocs\blog\commands\RunController.php(52): yii\console\Application->runAction('migrate/up', Array)
#12 [internal function]: app\commands\RunController->actionMigrate()
#13 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#14 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('migrate', Array)
#16 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('migrate', Array)
#17 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('run/migrate', Array)
#18 C:\xampp\htdocs\blog\commands\RunController.php(27): yii\console\Application->runAction('run/migrate')
#19 [internal function]: app\commands\RunController->actionInit()
#20 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#21 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#22 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('init', Array) #23 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('init', Array)
#24 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('run/init', Array)

#25 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('run/init', Array)
#26 C:\xampp\htdocs\blog\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#27 C:\xampp\htdocs\blog\yii(20): yii\base\Application->run()
#28 {main}
```

**Comment by rokorolov** [comment]
Yes there is a problem with foreign key. You need to update to dev version. Check this https://github.com/rokorolov/parus/issues/2
